ProjectQuickExam/urls.py
from django.contrib import admin
from django.urls import path, include  
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('user/', include('account.urls')),
    path('exams/', include('exams.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard', views.dashboard_view, name='dashboard'),
    path('about', views.about_view, name='about'),
    path('blogs', views.blogs_view, name='blogs'),
    path('feedback', views.feedback_view, name='feedback'),
    path('contact', views.contact_view, name='contact'),
    path('download', views.download_view, name='download'),
    path('terms_conditions', views.terms_conditions_view, name='terms_conditions'),
    path('blog/<str:blog_id>', views.blog_view, name='blog'),
   
]

exams/models.py
from django.contrib.auth.models import User
from django.db import models
import pandas as pd

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=15)


    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class finalExam(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    exam_file = models.FileField(upload_to='exam/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'FinalExams'

    def __str__(self):
        return self.title
    
    #call the function on exam save
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.exam_file:
            self.import_exam_from_excel()


    #function to extract excel file
    def import_exam_from_excel(self):
        
        #read excel file
        df = pd.read_excel(self.exam_file.path)

        #iterate over each row
        for index, row in df.iterrows():

            #extract question, text , choices, correctanswer form row
            question_text = row['Questions']
            choice1 = row['A']
            choice2 = row['B']
            choice3 = row['C']
            choice4 = row['D']
            correct_answer = row['Answer']
  
            # create the question object 
            question = Question.objects.get_or_create(exam=self, text=question_text)

            # create the choices object 
            choice_1 = Choice.objects.get_or_create(question=question[0], text=choice1, is_correct = correct_answer == 'A')
            choice_2 = Choice.objects.get_or_create(question=question[0], text=choice2, is_correct = correct_answer == 'B')
            choice_3 = Choice.objects.get_or_create(question=question[0], text=choice3, is_correct = correct_answer == 'C')
            choice_4 = Choice.objects.get_or_create(question=question[0], text=choice4, is_correct = correct_answer == 'D')

    

class Question(models.Model):
    exam = models.ForeignKey(finalExam, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text[:50]
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.question.text[:50]}, {self.text[:20]}"
    



class ExamSubmission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exam =  models.ForeignKey(finalExam, on_delete=models.CASCADE)
    score = models.IntegerField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}, {self.exam.title}"

templates/about.html
{% extends "./index.html" %}
{% block title %}About Us - QuickExam{% endblock title %}
{% block content %}

    <h1 class="display-4 text-center my-5">About Us</h1>


    <main>
        <div class="container col-md-8 col-sm-12">
            <section class="app-description">
                <h2>Welcome to QuickExam</h2>
                <p>
                    QuickExam is an exciting web app that brings you the latest and hottest exam topics in the world of
                    technology.
                    Sign up now to challenge your knowledge, learn new things, and have fun with our engaging exams.
                </p>
            </section>

            <section class="how-it-works">
                <h2>How It Works</h2>
                <p>
                    QuickExam offers a simple and intuitive user interface that allows you to:
                </p>
                <ul>
                    <li>Sign up and create your personalized account.</li>
                    <li>Choose from a variety of trending exam topics in the technology domain.</li>
                    <li>Participate in time-limited exams and answer questions to rank yourself on QuickExam.</li>
                    <li>Track your progress and compete with other tech enthusiasts on the leaderboard.</li>
                </ul>
            </section>
        </div>
    </main>

{% endblock content %}

templates/all-quiz.html
{% extends "./index.html" %}
{% block title %}All Exams - QuickExam{% endblock title %}
{% block content %}
    <h1 class="display-4 text-center my-5">All Exams</h1>

    <div class="container">
      <div class="d-flex flex-wrap">
        <a href="{% url 'all_exam' %}" class="btn btn-sm btn-light m-1">All</a>
        {% for category in categories %}
        <a href="{% url 'search' category.name %}" class="btn btn-sm btn-light m-1">{{category.name}}</a>
        {% endfor %}
      </div>
    </div>

    <form class="container d-flex my-3" role="search" method="get" action="{% url 'search' ' ' %}">
      {% csrf_token %}
      <input
        name="q"
        class="form-control me-2"
        type="search"
        placeholder="Search"
        aria-label="Search"
      />
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>

    <div class="container">
      <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3 g-3"> 
        {% if exams|length > 0 %}
        {% for exam in exams %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <h4>{{exam.title}}</h4>
              <p class="card-text">Total Questions - {{exam.question_set.all|length}}</p>
              <p class="card-text">
                {{exam.description|truncatewords:7}}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a 
                    href="{% url 'exam' exam.id %}"
                    class="btn btn-sm btn-outline-success"
                  >
                    Start
                </a>
                  
                </div>
                <small class="text-body-secondary">{{exam.created_at|timesince}} ago</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-lg-12 col-md-12 col-12">
          <p class="text-center text-danger fs-5">There is no exams available for this category or search.</p>
        </div>
        {% endif %}
      </div>

       
        
{% endblock content %}

templates/blogs.html
{% extends "./index.html" %}
{% block title %}Blogs - QuickExam{% endblock title %}
{% block content %}

    <h1 class="display-4 text-center my-5">Blogs</h1>

    <main>
        <div class="container col-md-6 col-sm-12">
            <ul class="list mb-4 p-3">
                <h3>2023</h3>
                <li class="d-flex justify-content-between mb-2">
                    <a href="./blog.html">Bootstrap 5.3.1</a>
                    <span title="26 Jul 23 08:05 UTC" class="text-secondary">Jul 26, 2023</span>
                </li>
                <li class="d-flex justify-content-between mb-2">
                    <a href="./blog.html">Bootstrap 5.3.1</a>
                    <span title="26 Jul 23 08:05 UTC" class="text-secondary">Jul 26, 2023</span>
                </li>
                <li class="d-flex justify-content-between mb-2">
                    <a href="./blog.html">Bootstrap 5.3.1</a>
                    <span title="26 Jul 23 08:05 UTC" class="text-secondary">Jul 26, 2023</span>
                </li>
            </ul>
            <ul class="list mb-4 p-3">
                <h3>2023</h3>
                <li class="d-flex justify-content-between mb-2">
                    <a href="./blog.html">Bootstrap 5.3.1</a>
                    <span title="26 Jul 23 08:05 UTC" class="text-secondary">Jul 26, 2023</span>
                </li>
                <li class="d-flex justify-content-between mb-2">
                    <a href="./blog.html">Bootstrap 5.3.1</a>
                    <span title="26 Jul 23 08:05 UTC" class="text-secondary">Jul 26, 2023</span>
                </li>
                <li class="d-flex justify-content-between mb-2">
                    <a href="./blog.html">Bootstrap 5.3.1</a>
                    <span title="26 Jul 23 08:05 UTC" class="text-secondary">Jul 26, 2023</span>
                </li>
            </ul>
        </div>
    </main>

{% endblock content %}

templates/confirm.html
{% extends "./index.html" %}
{% block title %}Delete {{request.user.username}}'s Profile - QuickExam{% endblock title %}
{% block content %}

  <h1 class="display-4 text-center my-5">Confirmation Page</h1>

  <div class="container">
    <form action="" method="POST" class="">
        {% csrf_token %}
        <p class="fs-4"><b>@{{request.user.username}}</b>, Are you sure you want to delete your profile?</p>
        <a href="{% url 'profile' request.user.username %}" class="btn btn-success" type="button">Back to Profile</a>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
  </div>

{% endblock content %}

templates/contactUs.html
{% extends "./index.html" %}
{% block title %}Contact Us - QuickExam{% endblock title %}
{% block content %}


	<h1 class="display-4 text-center my-5">Contact Us</h1>

	<main>
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6">
					<form action="#" method="post" class="contact-form">
						<div class="form-group mb-4">
							<label for="username">Username</label>
							<input type="text" id="username" name="username" value="Username" class="form-control"
								disabled>
						</div>

						<div class="form-group mb-4">
							<label for="subject">Subject</label>
							<input type="text" id="subject" name="subject" required class="form-control">
						</div>

						<div class="form-group mb-4">
							<label for="message">Message</label>
							<textarea id="message" name="message" rows="5" required class="form-control"></textarea>
						</div>

						<button type="submit" class="btn btn-primary btn-block">Send Message</button>
					</form>
				</div>
			</div>
		</div>
	</main>

{% endblock content %}

templates/dashboard.html
{% extends "./index.html" %}
{% block title %}Dashboard - QuickExam{% endblock title %}
{% block content %}

    <h1 class="display-4 text-center my-5">Dashboard</h1>

    <!-- Dashboard Code Goes Here -->
    <div class="container">
        <div class="row">
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center my-4 ">
                        <h1 class="card-title pricing-card-title">{{total_users}}</h1>
                        <p class="card-text">Active Users</p>
                        {% comment %} <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">2</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">150%</span>
                            </li>
                        </ul> {% endcomment %}
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center my-4">
                        <h1 class="card-title pricing-card-title">{{total_exams}}</h1>
                        <p class="card-text">Exams</p>
                        {% comment %} <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">2</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">150%</span>
                            </li>
                        </ul> {% endcomment %}
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center my-4">
                        <h1 class="card-title pricing-card-title">{{total_examSubmit}}</h1>
                        <p class="card-text">Submissions</p>
                        {% comment %} <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">2</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">150%</span>
                            </li>
                        </ul> {% endcomment %}
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center my-4">
                        <h1 class="card-title pricing-card-title">{{total_questions}}</h1>
                        <p class="card-text">Questions</p>
                        {% comment %} <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">2</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">150%</span>
                            </li>
                        </ul> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 col-md-12 my-3">
                <h2 class="mb-3 text-center">Inbox</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Username</th>
                            <th scope="col">Subject</th>
                            <th scope="col">Time</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="table-active">
                            <th scope="row">1</th>
                            <td><a href="">@Mark</a></td>
                            <td>Feedback for you</td>
                            <td>12 Aug, 2023</td>
                            <td><a href="" class="btn btn-sm btn-primary">Open</a></td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td colspan="2">Larry the Bird</td>
                            <td>@twitter</td>
                            <td><a href="" class="btn btn-sm btn-primary">Open</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

templates/feedback.html
{% extends "./index.html" %}
{% block title %}Feedback - QuickExam{% endblock title %}
{% block content %}
<h1 class="display-4 text-center my-5">Feedback</h1>

<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form action="#" method="post" class="contact-form">
                    <div class="form-group mb-4">
                        <label for="username">Name</label>
                        <input type="text" id="username" name="username" value="Username" class="form-control"
                            disabled>
                    </div>

                    <div class="form-group mb-4">
                        <label for="Email">Email</label>
                        <input type="email" id="email" name="email" class="form-control">
                    </div>

                    <div class="form-group mb-4">
                        <label for="subject">Feedback Subject</label>
                        <input type="text" id="subject" name="feedbackSubj" required class="form-control">
                    </div>

                    <div class="form-group mb-4">
                        <label for="message">Feedback</label>
                        <textarea id="message" name="feedback" rows="5" required class="form-control"></textarea>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block">Send Feedback</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> {% block title %}Welcome to QuickExam{% endblock title %} </title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" integrity="sha512-dPXYcDub/aeb08c63jRq/k6GaKccl256JQy/AnOq7CAnEZ9FzSL9wSbcZkMp4R26vBsMLFYH4kQ67/bbV8XaCQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
      href="{% static 'css/style.css' %}"
      rel="stylesheet"
    />
    {% comment %} <link
      href="{% static 'css/feedback.css' %}"
      rel="stylesheet"
    /> {% endcomment %}
    
  </head>
  <body>
    {% include "components/navbar.html" %}

    {% block content %}{% endblock content %}

    {% include "components/footer.html" %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script>
      const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
      const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
  </body>
</html>

templates/login.html
{% extends "index.html" %}
{% block title %}Login Page - QuickExam{% endblock title %}
{% block content %}
    <h1 class="display-4 text-center my-5">Login</h1>

    <div class="container">
      <div class="row row-cols-sm-1 row-cols-lg-3 container">
        <div class="col-12"></div>
        <div class="col-12">
          <div>
            {% for i in messages%}
              <h5 class="text-danger">{{i}}</h5>
            {% endfor %}
          </div>
            <form method="POST" action=""> 
              {% csrf_token %}
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label visually-hidden">Username</label>
                  <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Username" required>
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label visually-hidden">Password</label>
                  <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
                </div>
                <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1">
                  <label class="form-check-label" for="exampleCheck1">Remember me</label>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
                <p>New user |<a href="{% url 'register' %}"> Register</a></p>
              </form>
        </div>
        <div class="col-12"></div>
      </div>
    </div>
  {% endblock content %}

templates/profile-edit.html
{% extends "./index.html" %}
{% block title %}Edit {{request.user.username}}'s Profile - QuickExam{% endblock title %}
{% block content %}

  <h1 class="display-4 text-center my-5">Edit Profile</h1>


  <div class="container">
    <div class="row row-cols-sm-1 row-cols-lg-3 container">
      <div class="col-12">
      </div>
      <div class="col-12">

        

        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 d-flex justify-content-center">
                <img src="{{user_profile.profile_img.url}}" alt="profile-pic" width="150" height="150" class="rounded-circle">
            </div>

            <div class="mb-3">
                {% for msg in messages %}
                  <h5 class="text-danger">{{msg}}</h5>
                {% endfor %}
              </div>

          <div class="mb-3">
            <label for="exampleInputImage" class="form-label visually-hidden">Profile Image</label>
            <input type="file" name="profile_img" class="form-control" id="exampleInputImage">
          </div>
          <div class="mb-3">
            <label for="exampleInputFirstName" class="form-label visually-hidden">First Name</label>
            <input type="text" name="firstname" value="{{user_profile.user.first_name}}" class="form-control" id="exampleInputFirstName" placeholder="First Name" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputLastName" class="form-label visually-hidden">Last Name</label>
            <input type="text" name="lastname" value="{{user_profile.user.last_name}}" class="form-control" id="exampleInputLastName" placeholder="Last Name" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputEmail2" class="form-label visually-hidden">Email</label>
            <input type="email" name="email" value="{{user_profile.user.email}}" class="form-control" id="exampleInputEmail2" aria-describedby="emailHelp"
              placeholder="Email" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputUsername1" class="form-label visually-hidden">Username</label>
            <input type="text" name="username" value="{{user_profile.user.username}}" class="form-control" id="exampleInputUsername1" aria-describedby="emailHelp"
              placeholder="Username" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputLocation" class="form-label visually-hidden">Location</label>
            <input type="text" name="location" value="{{user_profile.location}}" class="form-control" id="exampleInputLocation" placeholder="Location" required>
          </div>
          
          <div class="mb-3">
            <label for="exampleInputGender" class="form-label visually-hidden">Gender</label>
            <select class="form-select form-control" name="gender" id="exampleInputGender" aria-label="Default select example" required>
                <option selected>Choose Your Gender</option>
                <option {% if user_profile.gender == 'Male' %}selected{% endif %} value="Male">Male</option>
                <option {% if user_profile.gender == 'Female' %}selected{% endif %} value="Female">Female</option>
                <option {% if user_profile.gender == 'Other' %}selected{% endif %} value="Other">Other</option>
              </select>
          </div>

          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label visually-hidden">Your Bio</label>
            <textarea class="form-control" value="" id="exampleFormControlTextarea1" name="bio" rows="3" placeholder="Your Bio" required>{{user_profile.bio}}</textarea>
          </div>
          
          <button type="submit" class="btn btn-success" name="">Save Profile</button>
        </form>
      </div>
      <div class="col-12">
      </div>
    </div>
  </div>




{% endblock content %}

templates/quiz.html
{% extends "./index.html" %} {% block title %}{{exam.title}} -
QuickExam{%endblock title %} {% block content %}
<h1 class="display-4 text-center my-5">
  {{exam.title}} - ({{exam.question_set.all|length}})
</h1>
<p class="fs-4 text-center container">{{exam.description}}</p>

<div class="container">
  <div class="d-flex justify-content-between">
    <span class="fs-5">{{exam.created_at}}</span>
    <span class="fs-5" id="timer">10:00</span>
  </div>

  {% for message in messages %}
  <div id="message-div">
    <h4 class="text-center text-success">{{message}}</h4>
  </div>
  {% endfor %}

  <div class="questions my-4">
    {% for question in exam.question_set.all %}
    <div class="card mb-3 question">
      <div class="card-header fw-bold">Question {{forloop.counter}}</div>
      <div class="card-body">
        <p class="card-text">{{forloop.counter}}. {{question.text}}</p>
        {% for option in question.choice_set.all %}
        <div class="form-check">
          <label class="form-check-label" for="{{option.id}}">
            <input
              class="form-check-input"
              value="{{option.text}}"
              type="radio"
              name="{{option.question.id}}"
              id="{{option.id}}"
            />

            {{option.text}}
          </label>
          {% if option.is_correct %}
          <span class="visually-hidden correct-answer">{{option.text}}</span>
          {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>

  <form action="" method="POST" id="exam-form">
    {% csrf_token %}
    <!-- hidden input feild for score -->
    <input type="hidden" name="score" value="0" id="user-score" />

    <!-- submit button -->
    <button type="submit" class="btn btn-primary" id="submit-button">
      Submit
    </button>
  </form>
</div>

<script>
  // Elements
  var submitButton = document.getElementById("submit-button");
  var timerSpan = document.getElementById("timer");
  var examForm = document.getElementById("exam-form");
  var questions = document.querySelectorAll(".question");
  var userScoreInput = document.getElementById("user-score");

  examDuration = questions.length * 60; //convert in sec

  //update Timer
  function updateTimer() {
    var min = Math.floor(examDuration / 60);
    var sec = examDuration % 60;

    timerSpan.innerText = min + "m" + sec + "s";

    // check if the time and ended
    if (examDuration <= 0) {
      //submit exam auto
      clearTimeout(examTimerId);
      submitExam();
    }
    else if (document.getElementById("message-div")) {
      clearTimeout(examTimerId);
      highlightCorrectAnswer();
    } 
    else {
      //decreament timer value by 1 sec
      examDuration--;
    }
  }

  // submit exam
  function submitExam() {
    // Cal score
    calculateScore();

    //submit from e
    examForm.submit();
  }

  //Check right answer and then calculate score
  function calculateScore() {
    var score = 0;

    questions.forEach((question) => {
      var selectedInput = question.querySelector("input:checked");
      var correctAnswer = question.querySelector(".correct-answer").innerText;
      // check if the answer is correct or not
      if (selectedInput && selectedInput.value === correctAnswer) {
        score += 1;
      }
    });

    //Update hidden input feild with score in form
    userScoreInput.value = score;
    // setTimeout(() => {

    //alert(`Your result is ${score}`);

    //document.getElementById("scoreDisplay").innerText = score;
    // }, 10000);
    //examForm.submit();

    // document.getElementById("scoreDisplay").innerText =  ` Your result is ${score}`;
    // clearTimeout(examTimerId);
  }

  //highlight correct answer while showing results
  function highlightCorrectAnswer(){
    questions.forEach(question => {
      var correctAnswer = question.querySelector(".correct-answer")
      correctAnswer.previousElementSibling.querySelector("input").classList.add("bg-success");
      correctAnswer.previousElementSibling.classList.add("fw-bold");
    });


    //disable submit button and all option
    submitButton.disabled = true;

    var options = document.querySelectorAll(".form-check-input");
    options.forEach(option => {
      option.disabled = true;
    });
  }

  //attach event listner to submit butoon
  submitButton.addEventListener("click", submitExam);

  // Timer interval
  examTimerId = setInterval(updateTimer, 1000);
</script>

{% endblock content %}